server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:33060/ht-video?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: yuqiu
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 63790
    password: hottube
    timeout: 6000ms
  rabbitmq:
    host: localhost
    port: 5672
    username: yuqiu
    password: yuqiu
    virtual-host: /

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.ht.model.entity

minio:
  endpoint: http://localhost:9000
  accessKey: yuqiu
  secretKey: yuqiu123
  bucket: ht-video

dubbo:
  application:
    name: ht-video
  registry:
    address: nacos://localhost:8848 # ?username=nacos&password=nacos
    register-mode: instance
  protocol:
    port: 0
  consumer:
    check: false
# cors config
cors:
  sources: localhost

video:
  base: /ht/video
  chunkSize: 5
