spring:
  datasource:
    url: jdbc:mysql://localhost:33060/ht-user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: yuqiu
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.ht.model.entity

server:
  port: 8081

minio:
  endpoint: http://localhost:9000
  accesskey: yuqiu
  secretkey: yuqiu123
  bucket: ht-user

jwt:
  secret-key: ht-user
  ttl: 7200000
  token-name: token

dubbo:
  application:
    name: ht-user
  registry:
    address: nacos://localhost:8848 # ?username=nacos&password=nacos
    register-mode: instance