server:
  port: 8084

dubbo:
  registry:
    register-mode: instance
    address: nacos://localhost:8848

cors:
  sources: localhost

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ht-browse
      username: yuqiu
      password: yuqiu123
  rabbitmq:
    host: localhost
    port: 5672
    username: yuqiu
    password: yuqiu
    virtual-host: /
